### ISSUE TITLE
Consider supporting single-value URI-enabled fields

### ISSUE THREAD

**Issue by jechols** [OregonDigital/oregondigital_2#108]
Solr seems to not like this:

Solrizer::InvalidIndexDescriptor in RecordsController#update
Invalid datatype `:"rdf/uri"'. Must be one of: :date, :time, :text, :text_en, :string, :symbol, :integer, :boolean

Somehow we must be converting arrays to be solr-friendly values, but not single-value RDF data.  Either we change our solrization stuff, wrap the values in an array explicitly (though this seems to make capybara hate me), or just say it's okay to never support single-value URI fields.

**Comment by jechols** [comment]
I'm not actually sure any longer how I got past Rails errors previously - hacking in an array (`Array.wrap` in `app/services/attribute_uri_converter.rb`) gives me a validation error that the field cannot be an array.  And if I save after wrapping the array, *all* URI fields turn into a string that's something like `#<TriplePoweredResource:0x007f3a2a49e560>`, even if the field supports multiple values.

Just running it as-is gives me the Solrizer error I described above, and the form shows that TriplePoweredResource string in the title field (the one I've hacked to only accept a single value).

I might be able to hack around this eventually, but I'm not sure it's worth the time.  An easier fix might be changing the Hydra validation such that properties that aren't allowed to have multiple values still allow arrays of a single element.  Then I *think* the `Array.wrap` approach could work.  I'll see if I can hack up hydra code to test this theory out....

**Comment by jechols** [comment]
So this is odd - I can't always duplicate the issue where trying to save an array in a non-multiple field causes all URI-enabled fields to show that odd TriplePoweredResource string.  But when it happens, it takes a *server restart* to get the multiple-value fields' URI data to work properly again.

**Comment by jechols** [comment]
Update: wrapping the array does *not* work.  The Solrizer error about rdf/uri is still present, which tells me that singular fields must have other kinds of magic going on (or else I've forgotten about some of the magic multi-value fields have)

**Comment by jechols** [comment]
Solrizer error goes away with a *second* AF hack to make singular fields still return the array instead of a single value.  Pretty sure that won't fly with the community, so a better approach would have to be figured out.

**Comment by jechols** [comment]
I achieved near success with some changes to how my hacked-up single-uri input... but:

- It still requires the above two hacks to ActiveFedora or else a different hack to get data into solr
- The "switch" button isn't present - we'd need to change something to enable that on ALL URI fields
- There's no way to modify the value because we don't allow modifications to fields that have a URI value

None of these are insurmountable, but the first and third items could take more time than it's worth for something we still aren't sure is useful.  I'll put up a branch (on my fork) in case we ever want to revisit this.

**Comment by jechols** [comment]
https://github.com/jechols/oregondigital_2/tree/feature/single-value-uri-fields

**Comment by mickeroo** [comment]
@jechols are we still considering doing this?

**Comment by jechols** [comment]
I don't feel like it's going to be worth our time at this point.  We don't need it for our use cases, I believe, and we probably no longer have the time to worry about "maybe others could use it someday"
