### ISSUE TITLE
Form Autocomplete for Controlled Vocabularies

### ISSUE THREAD

**Issue by terrellt** [OregonDigital/oregondigital_2#111]
There should be typeahead support.

**Comment by terrellt** [comment]
There's some discussion about whether we actually want typeahead vs an alternative.

**Comment by terrellt** [comment]
A problem we've had with typeahead and RDF URIs is that URIs by definition contain more context than their labels can share. If the primary entry point is typeahead then labels is the best we can do.

Rather than use typeahead there could be a process of multi-step enrichment and validation:

Step 1: Free-hand enter metadata. For subject, just type the word "Art". Finish up everything and submit.
Step 2: The item is ingested with text, but is marked as invalid for those fields which require URIs.
Step 3: Another screen is presented for enrichment. The UI for this is up in the air, but a way to select a vocabulary to search against (and display what the vocabulary is for (maybe using RDFS.comment for somewhere like http://id.loc.gov/authorities/subjects.nt ?)), show contextual information about a search result (http://id.loc.gov/authorities/subjects/sh85007461 might show alternative labels and the mads note `Here are entered general works on the visual arts. Works on the arts in general, including the visual arts, literature, and the performing arts, are entered under [Arts.]`) and let you pick one.
Step 4: Save. If all is valid, then it can marked as reviewed, otherwise continue enrichment.

**Comment by vantuyls** [comment]
So one problem with this is that you necessitate a review step in the input process, either by the submitter or by someone else (e.g. an admin of some sort). Is that a big deal for OD? I know it could be a big deal elsewhere.

**Comment by terrellt** [comment]
@vantuyls OD already has a review process, so I'm not sure it's a problem.

**Comment by tvc15brian** [comment]
@terrellt @vantuyls Our review process for OD certainly needs work in terms of ensuring that our controlled vocabs are accurately/consistently applied. What gets marked as reviewed and made live is entirely up to the project sponsor at this point. We have a number of live items that are a mess in terms of metadata (i.e., dates formatted incorrectly, filetype & actual object mismatch, wildly inconsistent use of AAT terms, etc.). Combined with training and data dictionaries, I think a multi-step enrichment and validation process will help us get this under control.

**Comment by terrellt** [comment]
This needs more discussion - probably on Monday. Moving it back to backlog.

**Comment by terrellt** [comment]
Will be solved by #267
