### ISSUE TITLE
Test the Fedora::Migrate script

### ISSUE THREAD

**Issue by mickeroo** [OregonDigital/oregondigital_2#12]
This is Esmé's script for migration

**Comment by terrellt** [comment]
Try from staging -> staging.

**Comment by terrellt** [comment]
Or try from local OD to local OD2

**Comment by mickeroo** [comment]
An FYI on the status of Fedora:Migrate : http://duraspace.org/articles/2606

**Comment by straleyb** [comment]
Status update on fedora migrate. I've been able to get it working locally. It was kind of a pain in the butt to get two jetty instances running next to each other. But after that was accomplished, I was able to play around with migrations, which were successful. I was able to transfer over about 100 items. Next I plan on finding out how to sanitize specific fields (mainly the set field, if it belongs to a set) which looks to be mucking up the solr index process. After I can get those indexed, its just checking to see if everything else transferred properly (rdf, derivatives, etc.)
