### ISSUE TITLE
Implement Collection A-Z List

### ISSUE THREAD

**Issue by terrellt** [OregonDigital/oregondigital_2#128]

**Comment by terrellt** [comment]
Need a mockup for what this should look like.

**Comment by mickeroo** [comment]
@mccallum Do we have any thoughts on what this should look like?

**Comment by mickeroo** [comment]
Depends on #223

**Comment by wickr** [comment]
How are defining 'New' for Collections from the wireframe?

Manual, if so, where/how is that specified?
Automatic, what criteria? We can obviously pull the most recent but probably don't want a brand new set with no items getting automatically featured.
