### ISSUE TITLE
Do collections need all metadata fields?

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/oregondigital_2#151]

**Comment by srabun** [comment]
We can ingest collections via form, right now it displays everything. Could there be a template for collections that has subset? Yes. Make a template and if you want to make a collection, hit collection template button.

**Comment by srabun** [comment]
Need to make vanity URLs work. Need displayed ID field, needs to be required but only for sets, not for anything else.

**Comment by terrellt** [comment]
Collections need to be able to define ID

**Comment by terrellt** [comment]
Right now this can be handled with templates.
