### ISSUE TITLE
Record should be able to be flagged for review after editing

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/oregondigital_2#204]

**Comment by straleyb** [comment]
@jsimic I just wanted to make sure that this ticket meant "After someone edits a record (either a reviewed or not reviewed record) there is an option to mark it as needing reviewed". So if someone goes into a public record that was already reviewed and edits a bunch of information, that it can be marked as needing review again.

**Comment by jsimic** [comment]
@straleyb : Yes, exactly.

**Comment by straleyb** [comment]
:+1: Thanks!

**Comment by terrellt** [comment]
@jsimic From the form?

**Comment by jsimic** [comment]
@terrellt You mean re-reviewable from the form? Yes, that would be nice, though I imagine I'd be more likely to just look at it in the review queue.

**Comment by terrellt** [comment]
@jsimic I mean when you edit a record, do you want a checkbox that says "Mark as needing review"?

**Comment by jsimic** [comment]
@terrellt Yes please.
