### ISSUE TITLE
When ingesting an object with a template it should hide fields not in the template beneath a button

### ISSUE THREAD

**Issue by terrellt** [OregonDigital/oregondigital_2#225]
Usability concerns? @jechols?

**Comment by jechols** [comment]
Having fields hidden by a button could be tricky.  But if they're hidden properly (you can look into this some on a site like webaim), they'll be hidden to sighted users while remaining accessible to screen readers after the "main" fields.  I think that would satisfy most users, given that sighted and blind users will have to wade through an equal amount of nonsense if they actually want/need a non-template field.

**Comment by jechols** [comment]
Hmm, we could probably make this whole thing really easy just by putting the `sr-only` class around the hidden fields, and remove it on clicking the button.  I think if the button is *below* such a div, it'll flow fairly naturally for screen readers.  We could stuff in `sr-only` headers "Core Fields" followed by "Other Fields" or something, to make it clear what matters on the form.

Or we figure out the screen-reader-friendly approach to dynamically showing and hiding the fields, but I am not sure what that would be....
