### ISSUE TITLE
Try PDF.JS

### ISSUE THREAD

**Issue by terrellt** [OregonDigital/oregondigital_2#229]

**Comment by lsat12357** [comment]
I've been using this url to test:
http://localhost:3000/testpdf/oregondigital:12345?track
the id is ignored, but the term at the end is used

**Comment by lsat12357** [comment]
oh, and the only buttons that work right now are the find next/prev

**Comment by lsat12357** [comment]
According to the video posted on github, the process starts with downloading the entire file and reading the xref table which is towards the end of the file.  Considering, eg., yearbooks, the book viewer continues to be a more viable option. Closing this for now.
