### ISSUE TITLE
Decide how to implement CV without generating code

### ISSUE THREAD

**Issue by mickeroo** [OregonDigital/oregondigital_2#23]

**Comment by terrellt** [comment]
May be done via #73, pending discussion.

**Comment by srabun** [comment]
Julia - would be nice, but not sure if it's worth it to pursue right now. Would be nice to be able to add new CVs ourselves, not having to use devs...

Trey - depends on use case...we can do both hardcode and database config. 

Julia is for it!

**Comment by terrellt** [comment]
https://github.com/OregonDigital/oregondigital_2/compare/feature/CVHackingTime

**Comment by srabun** [comment]
devs early on, then see use case and add admin panel (Jeremy)
