### ISSUE TITLE
Should records ingested with a template use that template when edited later?

### ISSUE THREAD

**Issue by terrellt** [OregonDigital/oregondigital_2#260]

**Comment by jechols** [comment]
Sounds like this is a "yes"... but we need to figure out what that means when a template is changed or even deleted.

**Comment by srabun** [comment]
answer is yes, just need to make it work.

Two problems - what happens if template is gone or changed? Give up and show all, if it changed, show whatever's there.

Julia says yes that's ok.

**Comment by straleyb** [comment]
The easy way. If the template is gone, show all fields. If the template has changed, show what fields are in the new version of the template.

**Comment by mickeroo** [comment]
See #266
