### ISSUE TITLE
We need fields for order and species in opaque namespace

### ISSUE THREAD

**Issue by mlv611** [OregonDigital/oregondigital_2#290]

**Comment by wickr** [comment]
@mlv611 What do you mean you need these fields in Opaque Namespace?

We have Order from Darwin Core in Oregon Digital: https://github.com/OregonDigital/oregondigital/blob/master/app/models/datastream/oregon_rdf.rb#L432

We also have Common Name (mapped to Darwin Core Vernacular Name) which might work for Species.
https://github.com/OregonDigital/oregondigital/blob/master/app/models/datastream/oregon_rdf.rb#L447
That one is controlled, and will accept uBio, itis, and opaquenamespace.org/ns/commonNames

We can easily add more Darwin Core fields if needed
