### ISSUE TITLE
Generate NOID on create

### ISSUE THREAD

**Issue by mickeroo** [OregonDigital/oregondigital_2#8]

**Comment by terrellt** [comment]
Hydra-Noid

**Comment by terrellt** [comment]
https://github.com/projecthydra-labs/active_fedora-noid

**Comment by jechols** [comment]
This is what I was thinking of: https://github.com/ndlib/noids - we compile a binary, stick it on a port nobody but our app can access, and mint noids via service.  There some interest for this in AF::Noid, but it isn't supported: https://groups.google.com/forum/#!topic/hydra-tech/ez9n8KF-MsA

**Comment by jechols** [comment]
Going with AF::Noid - long-term I would like to look at a service-based approach, but I think we should wait until AF::Identifier or similar (discussed briefly in the above google groups thread)

**Comment by terrellt** [comment]
:+1: I'm hoping that implementing AF::Noid means we might end up with the option for a configurable endpoint for noid minting in the future, for free.
